-- MySQL Script generated by MySQL Workbench
-- Sat 27 Aug 2016 01:13:01 PM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema taximetro
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `taximetro` ;

-- -----------------------------------------------------
-- Schema taximetro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `taximetro` DEFAULT CHARACTER SET utf8 ;
USE `taximetro` ;

-- -----------------------------------------------------
-- Table `taximetro`.`taxi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taximetro`.`taxi` (
  `idtaxi` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `plate` VARCHAR(100) NOT NULL,
  `idnum` VARCHAR(50) NOT NULL,
  `lastname1` VARCHAR(100) NULL,
  `lastname2` VARCHAR(100) NULL,
  `name` VARCHAR(100) NOT NULL,
  `base` VARCHAR(100) NULL,
  `service` VARCHAR(100) NULL,
  PRIMARY KEY (`idtaxi`),
  UNIQUE INDEX `plate_UNIQUE` (`plate` ASC),
  UNIQUE INDEX `idtaxi_UNIQUE` (`idtaxi` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taximetro`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taximetro`.`review` (
  `idreview` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `content` TEXT(500) NOT NULL,
  `likes` INT NOT NULL,
  `taxi_idtaxi` INT UNSIGNED NOT NULL,
  `fbid` VARCHAR(100) NOT NULL,
  `fbname` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idreview`, `taxi_idtaxi`),
  UNIQUE INDEX `idreview_UNIQUE` (`idreview` ASC),
  INDEX `fk_review_taxi_idx` (`taxi_idtaxi` ASC),
  CONSTRAINT `fk_review_taxi`
    FOREIGN KEY (`taxi_idtaxi`)
    REFERENCES `taximetro`.`taxi` (`idtaxi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
